#!/usr/bin/env ruby

# build .gem package
gem

# generate dnotes
dnote

# generate basic statistics
stats

# generate rdocs
rdoc do
  format 'redfish'
  exclude ['Redfile']
  output 'doc'
end

# generate ri docs
ridoc do
  output 'ri'
end

# run unit tests
testrb do
  tests 'test/*'
end

# publish website to github.com
grancher do
  active true
  #sitemap: [
  #  'site', 
  #  ['doc/rdoc', 'rdoc']
  #  ['doc/qedoc', 'qed']
  # ]
end

# publish gem to rubygems.org
gemcutter do
  active true
end

# send announcement to ruby-talk mailing list.
email do
  mailto "ruby-talk@ruby-lang.org"
#  from    : transfire@gmail.com
#  server  : <%= ENV['EMAIL_SERVER'] %>
#  port    : <%= ENV['EMAIL_PORT'] %>
#  account : <%= ENV['EMAIL_ACCOUNT'] %>
#  domain  : <%= ENV['EMAIL_DOMAIN'] %>
#  login   : <%= ENV['EMAIL_LOGIN'] %>
#  secure  : <%= ENV['EMAIL_SECURE'] %>
end

#
#vclog do
#  active false
#  format 'html' # xml, txt
#  layout 'rel'  # gnu
#  typed  false
#  output nil
#end

