#!/usr/bin/env ruby

box do
  types ['gem']
end

dnote

stats

rdoc do
  template 'redfish'
  exclude ['Syckfile']
  output 'doc'
end

ridoc do
  output 'ri'
end

testrb do
  tests 'test/*'
end

grancher do
  active true
  #sitemap: [
  #  'site', 
  #  ['doc/rdoc', 'rdoc']
  #  ['doc/qedoc', 'qed']
  # ]
end

gemcutter do
  active true
end

email do
  mailto "ruby-talk@ruby-lang.org"
#  from    : transfire@gmail.com
#  server  : <%= ENV['EMAIL_SERVER'] %>
#  port    : <%= ENV['EMAIL_PORT'] %>
#  account : <%= ENV['EMAIL_ACCOUNT'] %>
#  domain  : <%= ENV['EMAIL_DOMAIN'] %>
#  login   : <%= ENV['EMAIL_LOGIN'] %>
#  secure  : <%= ENV['EMAIL_SECURE'] %>
end

vclog do
  active false
  format 'html' # xml, txt
  layout 'rel'  # gnu
  typed  false
  output nil
end

